<div class="row">
    <div class="col-md-6 mb-3"><label>Cliente</label><select name="cliente_id" class="form-control" required><option value="">Selecciona</option>@foreach($clientes as $cliente)<option value="{{ $cliente->id }}" {{ old('cliente_id', $cobertura->cliente_id ?? '') == $cliente->id ? 'selected' : '' }}>{{ $cliente->nombre }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label>Modalidad</label><select name="modalidad_entrega" class="form-control" required><option value="domicilio" {{ old('modalidad_entrega', $cobertura->modalidad_entrega ?? '') == 'domicilio' ? 'selected' : '' }}>A domicilio</option><option value="ocurre" {{ old('modalidad_entrega', $cobertura->modalidad_entrega ?? '') == 'ocurre' ? 'selected' : '' }}>A ocurre</option></select></div>
    <div class="col-md-6 mb-3"><label>Oficina</label><select name="oficina_id" class="form-control"><option value="">Sin oficina</option>@foreach($oficinas as $oficina)<option value="{{ $oficina->id }}" {{ old('oficina_id', $cobertura->oficina_id ?? '') == $oficina->id ? 'selected' : '' }}>{{ optional($oficina->transportadora)->nombre }} - {{ $oficina->nombre }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label>Transportadora</label><select name="transportadora_id" class="form-control"><option value="">Sin transportadora</option>@foreach($transportadoras as $transportadora)<option value="{{ $transportadora->id }}" {{ old('transportadora_id', $cobertura->transportadora_id ?? '') == $transportadora->id ? 'selected' : '' }}>{{ $transportadora->nombre }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label>Bodega</label><select name="bodega_id" class="form-control"><option value="">Sin bodega</option>@foreach($bodegas as $bodega)<option value="{{ $bodega->id }}" {{ old('bodega_id', $cobertura->bodega_id ?? '') == $bodega->id ? 'selected' : '' }}>{{ $bodega->nombre }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label>Ciudad</label><input name="ciudad" class="form-control" value="{{ old('ciudad', $cobertura->ciudad ?? '') }}"></div>
    <div class="col-md-6 mb-3"><label>Estado</label><input name="estado" class="form-control" value="{{ old('estado', $cobertura->estado ?? '') }}"></div>
    <div class="col-md-3 mb-3"><label>Vigencia desde</label><input type="date" name="vigencia_desde" class="form-control" value="{{ old('vigencia_desde', isset($cobertura) && $cobertura->vigencia_desde ? $cobertura->vigencia_desde->format('Y-m-d') : '') }}"></div>
    <div class="col-md-3 mb-3"><label>Vigencia hasta</label><input type="date" name="vigencia_hasta" class="form-control" value="{{ old('vigencia_hasta', isset($cobertura) && $cobertura->vigencia_hasta ? $cobertura->vigencia_hasta->format('Y-m-d') : '') }}"></div>
    <div class="col-md-3 mb-3"><label>Estado</label><select name="activa" class="form-control"><option value="1" {{ old('activa', $cobertura->activa ?? true) ? 'selected' : '' }}>Activa</option><option value="0" {{ !old('activa', $cobertura->activa ?? true) ? 'selected' : '' }}>Inactiva</option></select></div>
    <div class="col-md-12 mb-3"><label>Observaciones</label><textarea name="observaciones" class="form-control">{{ old('observaciones', $cobertura->observaciones ?? '') }}</textarea></div>
</div>
